package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import kanta.rekisterinro;

import static kanta.rekisterinro.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 15:20:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class rekisterinroTest {


  // Generated by ComTest BEGIN
  /** testMain17 */
  @Test
  public void testMain17() {    // rekisterinro: 17
    rekisterinro rnr= new rekisterinro(); 
    boolean eka=rnr.tarkista("ZSR-745"); 
    boolean toka=rnr.tarkista("ZSR-4777"); 
    boolean kolmas=rnr.tarkista("tamaonvaintesti"); 
    boolean neljas=rnr.tarkista("ZSR_745"); 
    assertEquals("From: rekisterinro line: 23", true, eka); 
    assertEquals("From: rekisterinro line: 24", false, toka); 
    assertEquals("From: rekisterinro line: 25", false, kolmas); 
    assertEquals("From: rekisterinro line: 26", false, neljas); 

  } // Generated by ComTest END
}