package tietokanta_backendUusi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tietokanta_backendUusi.SailoException;
import tietokanta_backendUusi.Auto;
import tietokanta_backendUusi.Autot;

import static tietokanta_backendUusi.Autot.*;
// Generated by ComTest END

import java.io.File;
import java.io.FileNotFoundException;

/**
 * Test class made by ComTest
 * @version 2022.12.20 18:34:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AutotTest {



  // Generated by ComTest BEGIN
  /** testMain88 
 * @throws SailoException 
 * @throws FileNotFoundException */
  @Test
  public void testMain88() throws FileNotFoundException, SailoException {    // Autot: 88
    Autot autot = new Autot(); 
    Auto auto1 = new Auto(); 
    Auto auto2 = new Auto(); 
    Auto auto3 = new Auto(); 
    Auto auto4 = new Auto(); 
    auto1.taytaTiedot(1); 
    auto2.taytaTiedot(2); 
    auto3.taytaTiedot(2); 
    auto4.taytaTiedot(2); 
    String tiedosto= "testiautot.txt"; 
    autot.setTiedostonPerusNimi(tiedosto); 
    File testitiedosto= new File(tiedosto); 
    autot.lisaa(auto1); 
    autot.lisaa(auto2); 
    autot.lisaa(auto3); 
    autot.lisaa(auto4); 
    autot.tallenna(); 
    int lkm = autot.getLkm(); 
    assertEquals("From: Autot line: 107", 4, lkm); 
    autot.poista(auto1); 
    assertEquals("From: Autot line: 110", autot.getLkm(), 3); 
  } // Generated by ComTest END
}