package tietokanta_backendUusi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietokanta_backendUusi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.20 18:10:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AutoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi75 
 * @throws CloneNotSupportedException */
  @Test
  public void testRekisteroi75() throws CloneNotSupportedException {    // Auto: 75
    Auto auto1 = new Auto(); 
    Auto auto2 = new Auto(); 
    auto1.taytaTiedot(1); 
    auto1.rekisteroi(); 
    auto2.taytaTiedot(1); 
    auto2.rekisteroi(); 
    assertEquals("From: Auto line: 82", "1|mercedes-Bnez|c220|2017|125000|XYS-567|1999|Diesel|25000|toimiva peli|1", auto1.toString()); 
    assertEquals("From: Auto line: 83", "2|mercedes-Bnez|c220|2017|125000|XYS-567|1999|Diesel|25000|toimiva peli|1", auto2.toString()); 
    int n1= auto1.getTunnusNro(); 
    int n2=auto2.getTunnusNro(); 
    Auto auto3=auto2.clone(); 
    int n3=auto3.getTunnusNro(); 
    assertEquals("From: Auto line: 88", n2, n3); 
    Auto auto4 = new Auto(); 
    auto4.rekisteroi(); 
    auto4.taytaTiedot(); 
    int vuosimalli=Integer.parseInt(auto4.anna(2)); 
    assertEquals("From: Auto line: 93", 2017, vuosimalli); 
    assertEquals("From: Auto line: 94", n1+1, n2); 
  } // Generated by ComTest END
}