package tietokanta_backendUusi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tietokanta_backendUusi.SailoException;
import tietokanta_backendUusi.Liike;
import tietokanta_backendUusi.Liikkeet;

import static tietokanta_backendUusi.Liikkeet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.20 18:37:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** testMain64 
 * @throws SailoException */
  @Test
  public void testMain64() throws SailoException {    // Liikkeet: 64
    Liikkeet liikkeet = new Liikkeet(); 
    Liike liike = new Liike(); 
    Liike liike2 = new Liike(); 
    Liike liike3 = new Liike(); 
    assertEquals("From: Liikkeet line: 71", 0, liikkeet.getLkm()); 
    liikkeet.lisaa(liike); 
    assertEquals("From: Liikkeet line: 73", 1, liikkeet.getLkm()); 
    liikkeet.lisaa(liike2); 
    assertEquals("From: Liikkeet line: 75", 2, liikkeet.getLkm()); 
    liikkeet.lisaa(liike3); 
    assertEquals("From: Liikkeet line: 78", 3, liikkeet.getLkm()); 
    assertEquals("From: Liikkeet line: 79", liike, liikkeet.anna(0)); 
    liikkeet.poista(liike2.getLiikeID()); 
    assertEquals("From: Liikkeet line: 81", 2, liikkeet.getLkm()); 
  } // Generated by ComTest END
}