package tietokanta_backendUusi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietokanta_backendUusi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.20 18:29:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testParse119 */
  @Test
  public void testParse119() {    // Liike: 119
    Liike liike = new Liike(); 
    liike.parse("1| Makkosen auto|Vartujankatu 3||testi@gmail.com|0445147847|40100|kemi"); 
    assertEquals("From: Liike line: 122", 1, liike.getLiikeID()); 
    assertEquals("From: Liike line: 123", true, liike.toString().startsWith("1|Makkosen auto|Vartujankatu 3|")); 
    String osoite=liike.anna(2); 
    assertEquals("From: Liike line: 127", "Vartujankatu 3", osoite); 
    String nimi=liike.anna(1); 
    assertEquals("From: Liike line: 129", "Makkosen auto", nimi); 
  } // Generated by ComTest END
}