package tietokanta_backendUusi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tietokanta_backendUusi.Auto;
import tietokanta_backendUusi.Autot;
import tietokanta_backendUusi.Liike;
import tietokanta_backendUusi.SailoException;
import tietokanta_backendUusi.Tietokanta;

import static tietokanta_backendUusi.Tietokanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 16:08:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietokantaTest {



  // Generated by ComTest BEGIN
  /** testMain114 
 * @throws SailoException */
  @Test
  public void testMain114() throws SailoException {    // Tietokanta: 114
    Tietokanta tietokanta= new Tietokanta(); 
   
    Autot autot= new Autot(); 
    Auto auto= new Auto(); 
    auto.rekisteroi(); 
    Auto auto2= new Auto(); 
    auto2.rekisteroi(); 
    auto.taytaTiedot(); 
    auto2.taytaTiedot(); 
    Liike liike= new Liike(); 
    liike.rekisteroi(); 
    liike.taytaTiedot(); 
    tietokanta.lueTiedosto("testi"); 
    int t1 = tietokanta.autot.getLkm(); 
    tietokanta.lisaa(auto); 
    tietokanta.lisaa(auto2); 
    int t2= tietokanta.autot.getLkm(); 
    assertEquals("From: Tietokanta line: 105", t1+2, t2); 
    tietokanta.tallenna(); 
    tietokanta.poista(auto2); 
    Auto auto3= new Auto(); 
    Auto auto4= new Auto(); 
    auto3.rekisteroi(); 
    auto4.rekisteroi(); 
    Liike liike2=new Liike(); 
    liike2.rekisteroi(); 
    auto3.taytaTiedot(liike2.getLiikeID()); 
    auto4.taytaTiedot(liike2.getLiikeID()); 
    tietokanta.lisaa(liike2); 
    tietokanta.lisaa(auto3); 
    tietokanta.lisaa(auto3); 
     
    
    tietokanta.poista(liike2); 
    assertEquals("From: Tietokanta line: 147", "", liike2.getKaupunki()); 
    
    assertEquals(t2, t1+2); 
    tietokanta.tallenna(); 
  } // Generated by ComTest END
}