package tietokanta_backend.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tietokanta_backend.*;

/**
 * Test class made by ComTest
 * @version 2022.11.15 19:29:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AutoTest {


  // Generated by ComTest BEGIN
  /** testTulosta41 */
  @Test
  public void testTulosta41() {    // Auto: 41
    Auto auto1 = new Auto(); 
    Auto auto2 = new Auto(); 
    auto1.taytaTiedot(1, "Audi", "A3", 15800);
    auto1.rekisteroi(); 
   int n1=auto1.getTunnusNro(); 
    int n2= auto2.getTunnusNro(); 
    n2=n1+1; 
  } // Generated by ComTest END
}