package tietokanta_backend.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietokanta_backend.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.11.24 13:38:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {


  // Generated by ComTest BEGIN
  /** testLiike17 */
  @Test
  public void testLiike17() {    // Liike: 17
    Liike n1 = new Liike(); 
    n1.rekisteroi(); 
    Liike n2 = new Liike();
    n2.rekisteroi(); 
    int testin1= n1.getLiikeID(); 
    int testin2=n2.getLiikeID(); 
    assertEquals("From: Liike line: 24", 1, testin2-testin1); 
  } // Generated by ComTest END
}