package tietokanta_backend.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tietokanta_backend.Auto;
import tietokanta_backend.Liike;
import tietokanta_backend.SailoException;
import tietokanta_backend.Tietokanta;

import static tietokanta_backend.Tietokanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.11.24 13:54:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietokantaTest {



  // Generated by ComTest BEGIN
  /** testMain17 */
  @Test
  public void testMain17() {    // Tietokanta: 17
    Tietokanta tietokanta = new Tietokanta(); 
    Auto auto = new Auto(); 
    Auto auto2 = new Auto(); 
    auto.rekisteroi(); 
    auto2.rekisteroi(); 
    auto.taytaTiedot(2, "Audi", "A3", 18500); 
    auto2.taytaTiedot(3, "Volvo", "V70", 21250); 
    Liike liike= new Liike(); 
    liike.rekisteroi(); 
    liike.taytaTiedot("Makkosen rämä" , "veturintie 34" , "aws@gmail.com" , "0445131345",40950,"muurame"  ); 
    liike.tulosta(System.out); 
    try {
		tietokanta.lisaa(auto);
		tietokanta.lisaa(auto2); 
	    tietokanta.lisaa(liike); 
	} catch (SailoException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} 
     
    assertEquals("From: Tietokanta line: 39", 2, tietokanta.getAutojenMaara()); 
    assertEquals("From: Tietokanta line: 40", 1, tietokanta.getLiikkeidenMaara()); 
  } // Generated by ComTest END
}